# Полностью отключаем Jekyll
safe: true
lsi: false
incremental: false
highlighter: null
gist:
  noscript: false
kramdown:
  math_engine: null
  syntax_highlighter: null

# Отключаем все плагины
plugins: []

# Отключаем обработку CSS/SCSS
sass:
  load_paths: []
  style: compressed

# Разрешаем ВСЕ файлы
include:
  - "**/*"
  - ".nojekyll"
  
# Запрещаем обработку
exclude:
  - "*.scss"
  - "*.sass"
  - "*.coffee"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Устанавливаем пустую тему
theme: null
